### ISSUE TITLE
Player walk around

### ISSUE THREAD

**Issue by woodat** [woodat/test123#8]
as a player I want to
- [x] walk in the direction of the analogue stick
- [ ] be animated in the direction I'm walking
- [x] stop when I run into walls
